# ItemLimiter configuration file
# Report bugs and suggest features at:
# https://github.com/Wolfyxon/ItemLimiter

# WARNING: Do not set the values too low, or you will end up making a lot of players lose their valuable items!!!
# Maximum accepted item's NBT data size in bytes
maxItemDataSize: 3072
# Maximum amount of pages that books can have.
maxBookPages: 50

# Sends an alert to the admins when a player attempts to do these things
alerts:
  # When a player attempts to save a book that exceeds the data size limit
  bookSaveDataCancelled: true
  # When a player attempts to save a book that exceeds the page limit
  bookSavePagesCancelled: false
  # When a player attempts to drop an item exceeding the limit
  dropCleared: true

messages:
  noPermission: "&4Access denied."
  size: "&6Size of &2&l{itemName}&r: &d{size}b"
  itemRemoved: "&4{itemName} was removed from your inventory because it was a potentially dangerous item."
  itemsRemoved: "&4{count} items were removed from your inventory because they could potentially make you not able to join."
  bookSaveCancelledData: "&4Your book was not saved because it exceeded the maximum data size limit. Please don't attempt to create book/shulker bans."
  bookSaveCancelledPages: "$4Your book was not saved because it exceeded the maximum amount of pages ({max})."