# ItemLimiter configuration file
# Report bugs and suggest features at:
# https://github.com/Wolfyxon/ItemLimiter

# WARNING: Do not set the values too low, or you will end up making a lot of players lose their valuable items!!!
# Maximum accepted item's NBT data size in bytes. Avoid using values lower than 4096 as it's higher than a shulkerbox filled with player heads.
maxItemDataSize: 4096
# Maximum amount of pages that books can have. Minecraft's limit is 100 but various hacks and exploits are able to bypass it.
maxBookPages: 50

features:
  # Will trim edited book if it exceeds the page limit.
  bookTrimming: true
  # Master switch for scanning items.
  itemScanning: true
  # Will scan items when dropped (and remove if exceed limit)
  scanOnDrop: true
  # WIll scan items when picked up (and remove if exceed limit)
  scanOnPickup: true
  # Will scan the item in player's hand on click
  scanOnInteract: true
  # EXPERIMENTAL!!! This scanner is buggy, and it's still under construction. Avoid using as it's not effective and may cause loss of valuable items.
  scanOnInventoryClick: false

messages:
  noPermission: "&4Access denied."
  uncrecognizedOption: "&4Unrecognized option '{option}'"
  size: "&6Size of &2&l{itemName}&r: &d{size}b"
  notHolding: "&cYou're not holding any item!"
  itemRemoved: "&4{itemName} &cwas removed from your inventory because it was a potentially dangerous item."
  itemsRemoved: "&4{count} &citems were removed from your inventory because they could make you not able to join."
  cantDrop: "&cYou can't drop &4{itemName} &cbesaue it contains potentially dangerous data."
  cantPickup: "&cYou can't pick up &4{itemName} &cbesaue it contains potentially dangerous data."
  bookSaveCancelledPages: "&cSome of your book changes were not saved because they exceeded the &4{max} &cpage limit."