name: DataLimiter
version: '${project.version}'
main: com.wolfyxon.datalimiter.DataLimiter
api-version: 1.14
authors: [ Wolfyxon ]
description: A plugin that limits the size of data in items. Useful in preventing shulker/book bans
